config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("teacher_app.urls")),
    path("admin/", admin.site.urls),
]

teacher_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="home"),

    path("teacher/", views.teacher_list, name="teacher-list"),
    path("teacher/add/", views.teacher_add, name="teacher-add"),
    path("teacher/<str:pk>/summary/", views.teacher_summary, name="teacher-summary"),
    path("teacher/<str:pk>/update/", views.teacher_update, name="teacher-update"),
    path("teacher/<str:pk>/delete/", views.teacher_delete, name="teacher-delete"),

    path("course/", views.course_list, name="course-list"),
    path("course/add/", views.CourseCreateView.as_view(), name="course-add"),
    path("course/<str:pk>/update/", views.CourseUpdateView.as_view(), name="course-update"),
    path("course/<str:pk>/", views.course_detail, name="course-detail"),
    path("course/<str:pk>/delete/", views.course_delete, name="course-delete"),

    path("project/", views.project_list, name="project-list"),
    path("project/add/", views.ProjectCreateView.as_view(), name="project-add"),
    path("project/<str:pk>/update/", views.ProjectUpdateView.as_view(), name="project-update"),
    path("project/<str:pk>/", views.project_detail, name="project-detail"),
    path("project/<str:pk>/delete/", views.project_delete, name="project-delete"),

    path("paper/", views.paper_list, name="paper-list"),
    path("paper/add/", views.PaperCreateView.as_view(), name="paper-add"),
    path("paper/<str:pk>/update/", views.PaperUpdateView.as_view(), name="paper-update"),
    path("paper/<str:pk>/", views.paper_detail, name="paper-detail"),
    path("paper/<str:pk>/delete/", views.paper_delete, name="paper-delete"),
]

teacher_app/models.py
from django.db import models
from django.db.models import F, Q


class Teacher(models.Model):
    GENDER_CHOICES = {
        1: "男",
        2: "女",
    }

    TITLE_CHOICES = {
        1: "博士后",
        2: "助教",
        3: "讲师",
        4: "副教授",
        5: "特任教授",
        6: "教授",
        7: "助理研究员",
        8: "特任副研究员",
        9: "副研究员",
        10: "特任研究员",
        11: "研究员",
    }

    id = models.CharField(max_length=5, primary_key=True, verbose_name="工号")
    name = models.CharField(max_length=200, verbose_name="姓名")
    gender = models.IntegerField(choices=GENDER_CHOICES, verbose_name="性别")
    title = models.IntegerField(choices=TITLE_CHOICES, verbose_name="职称")

    class Meta:
        verbose_name = "教师"

    def __str__(self):
        return f"{self.id} {self.name}"


class Course(models.Model):
    COURSE_KIND_CHOICES = {
        1: "本科生课程",
        2: "研究生课程",
    }

    id = models.CharField(max_length=256, primary_key=True, verbose_name="课程号")
    name = models.CharField(max_length=256, verbose_name="课程名")
    total_hours = models.PositiveIntegerField(verbose_name="总学时")
    kind = models.IntegerField(choices=COURSE_KIND_CHOICES, verbose_name="课程性质")
    teachers = models.ManyToManyField(Teacher, through="TeacherCourse")

    class Meta:
        verbose_name = "课程"

    def __str__(self):
        return f"{self.id} {self.name}"


class Project(models.Model):
    PROJECT_KIND_CHOICES = {
        1: "国家级项目",
        2: "省部级项目",
        3: "市厅级项目",
        4: "企业合作项目",
        5: "其它类型项目",
    }

    id = models.CharField(max_length=256, primary_key=True, verbose_name="项目号")
    name = models.CharField(max_length=256, verbose_name="项目名称")
    source = models.CharField(max_length=256, verbose_name="项目来源")
    kind = models.IntegerField(choices=PROJECT_KIND_CHOICES, verbose_name="项目类型")
    total_fund = models.FloatField(verbose_name="总经费")
    start_year = models.PositiveIntegerField(verbose_name="开始年份")
    end_year = models.PositiveIntegerField(verbose_name="结束年份")
    teachers = models.ManyToManyField(Teacher, through="TeacherProject")

    class Meta:
        verbose_name = "项目"
        constraints = [
            models.CheckConstraint(
                check=models.Q(start_year__lte=F("end_year")),
                name="start_year_lte_end_year",
                violation_error_message="开始年份应小于或等于结束年份",
            )
        ]

    def __str__(self):
        return f"{self.id} {self.name}"


class Paper(models.Model):
    PAPER_KIND_CHOICES = {
        1: "full paper",
        2: "short paper",
        3: "poster paper",
        4: "demo paper",
    }

    PAPER_LEVEL_CHOICES = {
        1: "CCF-A",
        2: "CCF-B",
        3: "CCF-C",
        4: "中文 CCF-A",
        5: "中文 CCF-B",
        6: "无级别",
    }

    id = models.PositiveIntegerField(primary_key=True, verbose_name="序号")
    title = models.CharField(max_length=256, verbose_name="论文名称")
    source = models.CharField(max_length=256, verbose_name="发表源")
    pub_year = models.PositiveIntegerField(verbose_name="发表年份")
    kind = models.IntegerField(choices=PAPER_KIND_CHOICES, verbose_name="类型")
    level = models.IntegerField(choices=PAPER_LEVEL_CHOICES, verbose_name="级别")
    teachers = models.ManyToManyField(Teacher, through="TeacherPaper")

    class Meta:
        verbose_name = "论文"

    def __str__(self):
        return f"{self.id}《{self.title}》"


class TeacherCourse(models.Model):
    SEMESTER_CHOICES = {
        1: "春季学期",
        2: "夏季学期",
        3: "秋季学期",
    }

    teacher = models.ForeignKey(
        "Teacher", on_delete=models.PROTECT, verbose_name="教师"
    )
    course = models.ForeignKey("Course", on_delete=models.CASCADE, verbose_name="课程")
    year = models.PositiveIntegerField(verbose_name="年份")
    semester = models.IntegerField(choices=SEMESTER_CHOICES, verbose_name="学期")
    hours = models.PositiveIntegerField(verbose_name="学时")

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["teacher", "course", "year", "semester"],
                name="unique_teacher_course_year_semester",
                violation_error_message="授课教师重复",
            ),
        ]


class TeacherProject(models.Model):
    teacher = models.ForeignKey(
        "Teacher", on_delete=models.PROTECT, verbose_name="教师"
    )
    project = models.ForeignKey(
        "Project", on_delete=models.CASCADE, verbose_name="项目"
    )
    rank = models.PositiveIntegerField(verbose_name="排名")
    fund = models.FloatField(verbose_name="承担经费")

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["teacher", "project"],
                name="unique_teacher_project",
                violation_error_message="承担教师重复",
            ),
            models.UniqueConstraint(
                fields=["project", "rank"],
                name="unique_project_rank",
                violation_error_message="排名重复",
            ),
        ]


class TeacherPaper(models.Model):
    teacher = models.ForeignKey(
        "Teacher", on_delete=models.PROTECT, verbose_name="教师"
    )
    paper = models.ForeignKey("Paper", on_delete=models.CASCADE, verbose_name="论文")
    rank = models.PositiveIntegerField(verbose_name="排名")
    corresp = models.BooleanField(verbose_name="是否通讯作者")

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["teacher", "paper"],
                name="unique_teacher_paper",
                violation_error_message="作者重复",
            ),
            models.UniqueConstraint(
                fields=["paper", "rank"],
                name="unique_paper_rank",
                violation_error_message="排名重复",
            ),
            models.UniqueConstraint(
                fields=["paper"],
                condition=Q(corresp=True),
                name="unique_paper_corresp",
                violation_error_message="一篇论文只能有一个通讯作者",
            ),
        ]

teacher_app/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.db.models import ProtectedError
from django.views import View
from django.views.decorators.http import require_http_methods

from .forms import *
from .filters import *


def index(request):
    return redirect("teacher-list")


def teacher_list(request):
    filter = TeacherFilter(request.GET or None, queryset=Teacher.objects.all())
    teacher_list = filter.qs
    context = {"filter": filter, "teacher_list": teacher_list}
    return render(request, "teacher_app/teacher_list.html", context)


def teacher_add(request):
    form = TeacherForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            teacher = form.save()
            messages.success(request, f"教师 {teacher.name} 登记成功！")
            return redirect("teacher-list")

    context = {"form": form}
    return render(request, "teacher_app/teacher_form.html", context)


def teacher_update(request, pk):
    teacher = get_object_or_404(Teacher, pk=pk)
    form = TeacherForm(request.POST or None, instance=teacher)
    form.fields["id"].disabled = True

    if request.method == "POST":
        if form.is_valid():
            teacher = form.save()
            messages.success(request, f"教师 {teacher.name} 更新成功！")
            return redirect("teacher-list")

    context = {"form": form}
    return render(request, "teacher_app/teacher_form.html", context)


@require_http_methods(["POST"])
def teacher_delete(request, pk):
    teacher = get_object_or_404(Teacher, pk=pk)

    try:
        s = str(teacher)
        teacher.delete()
        messages.success(request, f"教师 {s} 删除成功！")
    except ProtectedError:
        messages.error(request, f"无法删除教师 {teacher}：存在关联数据")

    return redirect("teacher-list")


def teacher_summary(request, pk):
    teacher = get_object_or_404(Teacher, pk=pk)
    form = YearRangeForm(request.GET or None)
    context = {"teacher": teacher}

    if request.GET:
        form = YearRangeForm(request.GET)
        if form.is_valid():
            start_year = form.cleaned_data["start_year"]
            end_year = form.cleaned_data["end_year"]

            teachercourse_list = TeacherCourse.objects.filter(
                Q(teacher=teacher),
                Q(year__gte=start_year),
                Q(year__lte=end_year),
            )

            teacherpaper_list = TeacherPaper.objects.filter(
                Q(teacher=teacher),
                Q(paper__pub_year__gte=start_year),
                Q(paper__pub_year__lte=end_year),
            )

            teacherproject_list = TeacherProject.objects.filter(
                Q(teacher=teacher),
                Q(project__start_year__lte=end_year),
                Q(project__end_year__gte=start_year),
            )

            context.update(
                {
                    "start_year": start_year,
                    "end_year": end_year,
                    "teachercourse_list": teachercourse_list,
                    "teacherpaper_list": teacherpaper_list,
                    "teacherproject_list": teacherproject_list,
                }
            )

    context["form"] = form
    return render(request, "teacher_app/teacher_summary.html", context)


def course_list(request):
    filter = CourseFilter(request.GET or None, queryset=Course.objects.all())
    course_list = filter.qs.distinct()
    context = {"filter": filter, "course_list": course_list}

    return render(request, "teacher_app/course_list.html", context)


class CreateWithInlinesView(View):
    model = None
    form_class = None
    formset_class = None
    template_name = "teacher_app/form_with_inlines.html"
    success_redirect = None

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        formset = self.formset_class()
        context = {
            "model_name": self.model._meta.verbose_name,
            "form": form,
            "formset": formset
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        formset = self.formset_class(request.POST)

        model_name = self.model._meta.verbose_name

        if form.is_valid():
            object = form.save(commit=False)
            formset.instance = object

            if formset.is_valid():
                object.save()
                formset.save()
                messages.success(request, f"{model_name} {object} 登记成功！")
                return redirect(self.success_redirect)

        context = {
            "model_name": model_name,
            "form": form,
            "formset": formset
        }
        return render(request, self.template_name, context)


class UpdateWithInlinesView(View):
    model = None
    form_class = None
    formset_class = None
    template_name = "teacher_app/form_with_inlines.html"
    success_redirect = None

    def get(self, request, *args, **kwargs):
        object = get_object_or_404(self.model, pk=kwargs.get("pk"))
        form = self.form_class(instance=object)
        form.fields["id"].disabled = True
        formset = self.formset_class(instance=object)

        context = {
            "model_name": self.model._meta.verbose_name,
            "form": form,
            "formset": formset
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        object = get_object_or_404(self.model, pk=kwargs.get("pk"))
        form = CourseForm(request.POST, instance=object)
        form.fields["id"].disabled = True
        formset = TeacherCourseFormSet(request.POST, instance=object)

        model_name = self.model._meta.verbose_name

        if form.is_valid() and formset.is_valid():
            formset.instance = form.save()
            formset.save()
            messages.success(request, f"{model_name} {object} 更新成功！")
            return redirect(self.success_redirect)

        context = {
            "model_name": model_name,
            "form": form,
            "formset": formset,
        }
        return render(request, "teacher_app/form_with_inlines.html", context)


def course_detail(request, pk):
    course = get_object_or_404(Course, pk=pk)
    context = {"course": course}
    return render(request, "teacher_app/course_detail.html", context)


class CourseCreateView(CreateWithInlinesView):
    model = Course
    form_class = CourseForm
    formset_class = TeacherCourseFormSet
    success_redirect = "course-list"


class CourseUpdateView(UpdateWithInlinesView):
    model = Course
    form_class = CourseForm
    formset_class = TeacherCourseFormSet
    success_redirect = "course-list"


@require_http_methods(["POST"])
def course_delete(request, pk):
    course = get_object_or_404(Course, pk=pk)
    s = str(course)
    course.delete()
    messages.success(request, f"课程 {s} 删除成功！")
    return redirect("course-list")


def project_list(request):
    filter = ProjectFilter(request.GET or None, queryset=Project.objects.all())
    project_list = filter.qs.distinct()
    context = {"filter": filter, "project_list": project_list}

    return render(request, "teacher_app/project_list.html", context)


def paper_detail(request, pk):
    paper = get_object_or_404(Paper, pk=pk)
    context = {"paper": paper}
    return render(request, "teacher_app/paper_detail.html", context)


class ProjectCreateView(CreateWithInlinesView):
    model = Project
    form_class = ProjectForm
    formset_class = TeacherProjectFormSet
    success_redirect = "project-list"


class ProjectUpdateView(UpdateWithInlinesView):
    model = Project
    form_class = ProjectForm
    formset_class = TeacherProjectFormSet
    success_redirect = "project-list"


def project_detail(request, pk):
    project = get_object_or_404(Project, pk=pk)
    context = {"project": project}
    return render(request, "teacher_app/project_detail.html", context)


@require_http_methods(["POST"])
def project_delete(request, pk):
    project = get_object_or_404(Project, pk=pk)
    s = str(project)
    project.delete()
    messages.success(request, f"项目 {s} 删除成功！")
    return redirect("project-list")


def paper_list(request):
    filter = PaperFilter(request.GET or None, queryset=Paper.objects.all())
    paper_list = filter.qs.distinct()
    context = {"filter": filter, "paper_list": paper_list}
    return render(request, "teacher_app/paper_list.html", context)


class PaperCreateView(CreateWithInlinesView):
    model = Paper
    form_class = PaperForm
    formset_class = TeacherPaperFormSet
    success_redirect = "paper-list"


class PaperUpdateView(UpdateWithInlinesView):
    model = Paper
    form_class = PaperForm
    formset_class = TeacherPaperFormSet
    success_redirect = "paper-list"


@require_http_methods(["POST"])
def paper_delete(request, pk):
    paper = get_object_or_404(Paper, pk=pk)
    s = str(paper)
    paper.delete()
    messages.success(request, f"论文 {s} 删除成功！")
    return redirect("paper-list")

teacher_app/templates/teacher_app/course_list.html
{% extends "teacher_app/base.html" %}
{% block content %}

{% include "teacher_app/filter_accordion.html" %}
<hr>

<div>
  <a class="btn btn-outline-primary my-2" href="{% url 'course-add' %}" role="button">+ 添加课程</a>

  <table class="table table-hover text-center">
    <thead>
    <tr>
      <th scope="col">课程号</th>
      <th scope="col">课程名称</th>
      <th scope="col">学时数</th>
      <th scope="col">课程性质</th>
      <th scope="col">操作</th>
    </tr>
    </thead>

    <tbody>
    {% for course in course_list %}
      <tr>
        <td>{{ course.id }}</td>
        <td>{{ course.name }}</td>
        <td>{{ course.total_hours }}</td>
        <td>{{ course.get_kind_display }}</td>
        <td>
          <a role="button" class="btn btn-primary" href="{% url "course-detail" course.id %}">详情</a>
          <a role="button" class="btn btn-warning" href="{% url "course-update" course.id %}">更新</a>
          <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal"
                  data-bs-name="课程 {{ course }}" data-bs-href="{% url "course-delete" course.id %}">删除
          </button>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

{% include "teacher_app/delete_modal.html" %}

{% endblock %}

teacher_app/templates/teacher_app/delete-modal.html
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        确认要删除<span id="object-name">...</span>吗？
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
        <form id="delete-modal-form" action="#" method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">确定</button>
        </form>
      </div>
    </div>
  </div>
</div>

<script>
  const deleteModal = document.getElementById("deleteModal")
  if (deleteModal) {
    deleteModal.addEventListener("show.bs.modal", event => {
      const button = event.relatedTarget
      const name = button.getAttribute("data-bs-name")
      const href = button.getAttribute("data-bs-href")
  
      const objectName = deleteModal.querySelector("#object-name")
      objectName.textContent = name

      const modalForm = deleteModal.querySelector("#delete-modal-form")
      modalForm.action = href
    })
  }
</script>

teacher_app/templates/teacher_app/paper_detail.html
{% extends "teacher_app/base.html" %}
{% block content %}

<h2>项目信息</h2>

<table class="table text-center">
  <thead>
  <tr>
    <th scope="col">序号</th>
    <th scope="col">论文名称</th>
    <th scope="col">发表源</th>
    <th scope="col">发表年份</th>
    <th scope="col">类型</th>
    <th scope="col">级别</th>
  </tr>
  </thead>

  <tbody>
  <tr>
    <td>{{ paper.id }}</td>
    <td>{{ paper.title }}</td>
    <td>{{ paper.source }}</td>
    <td>{{ paper.pub_year }}</td>
    <td>{{ paper.get_kind_display }}</td>
    <td>{{ paper.get_level_display }}</td>
  </tr>
  </tbody>
</table>

<h2>作者</h2>

<table class="table text-center">
  <thead>
  <tr>
    <th scope="col">职工号</th>
    <th scope="col">姓名</th>
    <th scope="col">排名</th>
    <th scope="col">是否通讯作者</th>
  </tr>
  </thead>

  <tbody>
  {% for record in paper.teacherpaper_set.all %}
    <tr>
      <td scope="col">{{ record.teacher.id }}</td>
      <td>{{ record.teacher.name }}</td>
      <td>{{ record.rank }}</td>
      <td>{% if record.corresp %} 是 {% else %} - {% endif %}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock content %}

teacher_app/templates/teacher_app/paper_list.html
{% extends "teacher_app/base.html" %}
{% block content %}

{% include "teacher_app/filter_accordion.html" %}
<hr>

<div>
  <a class="btn btn-outline-primary my-2" href="{% url 'paper-add' %}" role="button">+ 添加论文</a>

  <table class="table table-hover text-center">
    <thead>
    <tr>
      <th scope="col">序号</th>
      <th scope="col">论文名称</th>
      <th scope="col">发表源</th>
      <th scope="col">发表年份</th>
      <th scope="col">类型</th>
      <th scope="col">级别</th>
      <th scope="col">操作</th>
    </tr>
    </thead>

    <tbody>
    {% for paper in paper_list %}
      <tr>
        <td>{{ paper.id }}</td>
        <td>{{ paper.title }}</td>
        <td>{{ paper.source }}</td>
        <td>{{ paper.pub_year }}</td>
        <td>{{ paper.get_kind_display }}</td>
        <td>{{ paper.get_level_display }}</td>
        <td>
          <a role="button" class="btn btn-primary" href="{% url 'paper-detail' paper.id %}">详情</a>
          <a role="button" class="btn btn-warning" href="{% url 'paper-update' paper.id %}">更新</a>
          <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal"
                  data-bs-name="论文 {{ paper }}" data-bs-href="{% url 'paper-delete' paper.id %}">删除
          </button>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

{% include "teacher_app/delete_modal.html" %}

{% endblock %}

teacher_app/templates/teacher_app/project_list.html
{% extends "teacher_app/base.html" %}
{% block content %}

{% include "teacher_app/filter_accordion.html" %}
<hr>

<div>
  <a class="btn btn-outline-primary my-2" href="{% url 'project-add' %}" role="button">+ 添加项目</a>

  <table class="table table-hover text-center">
    <thead>
    <tr>
      <th scope="col">项目号</th>
      <th scope="col">项目名称</th>
      <th scope="col">项目来源</th>
      <th scope="col">项目类型</th>
      <th scope="col">总经费</th>
      <th scope="col">年份</th>
      <th scope="col">操作</th>
    </tr>
    </thead>

    <tbody>
    {% for project in project_list %}
      <tr>
        <td>{{ project.id }}</td>
        <td>{{ project.name }}</td>
        <td>{{ project.source }}</td>
        <td>{{ project.get_kind_display }}</td>
        <td>{{ project.total_fund }}</td>
        <td>{{ project.start_year }}-{{ project.end_year }}</td>
        <td>
          <a role="button" class="btn btn-primary" href="{% url 'project-detail' project.id %}">详情</a>
          <a role="button" class="btn btn-warning" href="{% url 'project-update' project.id %}">更新</a>
          <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal"
                  data-bs-name="项目 {{ project }}" data-bs-href="{% url 'project-delete' project.id %}">删除
          </button>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

{% include "teacher_app/delete_modal.html" %}
{% endblock %}

teacher_app/templates/teacher_app/teacher_form.html
{% extends "teacher_app/base.html" %}

{% load django_bootstrap5 %}

{% block content %}

<form method="POST">
  {% csrf_token %}
  {% bootstrap_form form layout="horizontal" %}
  <button class="btn btn-primary" type="submit">确认</button>
  <button class="btn btn-secondary" type="reset">重置</button>
</form>

{% endblock content %}

teacher_app/templates/teacher_app/teacher_list.html
{% extends "teacher_app/base.html" %}
{% block content %}

{% include "teacher_app/filter_accordion.html" %}
<hr>

<div>
  <a class="btn btn-outline-primary my-2" href="{% url 'teacher-add' %}" role="button">+ 添加教师</a>

  <table class="table table-hover text-center">
    <thead>
    <tr>
      <th scope="col">工号</th>
      <th scope="col">姓名</th>
      <th scope="col">性别</th>
      <th scope="col">职称</th>
      <th scope="col">操作</th>
    </tr>
    </thead>

    <tbody>
    {% for teacher in teacher_list %}
      <tr>
        <td>{{ teacher.id }}</td>
        <td>{{ teacher.name }}</td>
        <td>{{ teacher.get_gender_display }}</td>
        <td>{{ teacher.get_title_display }}</td>
        <td>
          <a class="btn btn-primary" href="{% url 'teacher-summary' teacher.id %}" role="button">工作统计</a>
          <a class="btn btn-warning" href="{% url 'teacher-update' teacher.id %}" role="button">更新</a>
          <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal"
                  data-bs-name="教师 {{ teacher }}" data-bs-href="{% url 'teacher-delete' teacher.id %}">删除
          </button>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

{% include "teacher_app/delete_modal.html" %}

{% endblock content %}

teacher_app/templates/teacher_app/teacher_summary.html
{% extends "teacher_app/base.html" %}

{% load django_bootstrap5 %}

{% block content %}

<div class="d-flex justify-content-center d-print-none">
  <form method="get">
    <div class="row g-3 my-2 align-items-center">
      {% for field in form %}
        {% bootstrap_field field wrapper_class="col-auto my-2" show_label=False %}
      {% endfor %}

      <div class="col-auto my-2">
        <div class="row g-2">
          <div class="col">
            <button class="btn btn-success col" type="submit">生成</button>
          </div>
          <div class="col"><a class="btn btn-primary col" href="javascript:self.print()">打印</a></div>
          <div class="col"><a class="btn btn-secondary col" href="{% url 'teacher-list' %}">返回</a></div>
        </div>
      </div>
    </div>
  </form>
</div>

<hr class="mt-1 mb-5 boarder d-print-none">

<style>
  @media print {
    body {
      font-size: smaller;
    }
  }

  hr {
    margin: 0;
  }

  ol {
    padding-left: 0;
  }

  ol li {
    margin-left: 1em;
  }
</style>

<h5 class="d-flex justify-content-center">
  教师教学科研工作统计{% if start_year is not None %}（{{ start_year }}-{{ end_year }}）{% endif %}
</h5>

<div class="my-4">
  <h6>教师基本信息</h6>
  <hr class="border border-black opacity-100">


  <ul class="my-2 list-inline">
    <li class="list-inline-item me-3">工号：{{ teacher.id }}</li>
    <li class="list-inline-item me-3">姓名：{{ teacher.name }}</li>
    <li class="list-inline-item me-3">性别：{{ teacher.get_gender_display }}</li>
    <li class="list-inline-item">职称：{{ teacher.get_title_display }}</li>
  </ul>
</div>

{% if teachercourse_list %}
  <div class="my-4">
    <h6>教学情况</h6>
    <hr class="border border-black opacity-100">

    <ul class="list-unstyled my-2">
      {% for record in teachercourse_list %}
        <li>
          <ul class="list-inline">
            <li class="list-inline-item me-3">课程号：{{ record.course.id }}</li>
            <li class="list-inline-item me-3">课程名：{{ record.course.name }}</li>
            <li class="list-inline-item me-3">主讲学时：{{ record.hours }}</li>
            <li class="list-inline-item">学期：{{ record.year }} {{ record.get_semester_display | first }}</li>
          </ul>
        </li>
      {% endfor %}
    </ul>
  </div>
{% endif %}

{% if teacherpaper_list %}
  <div class="my-4">
    <h6>发表论文情况</h6>
    <hr class="border border-black opacity-100">

    <ol class="my-2">
      {% for record in teacherpaper_list %}
        <li>
          {{ record.paper.title }}，{{ record.paper.source }}，{{ record.paper.pub_year }}，{{ record.paper.get_level_display }}，排名第
          {{ record.rank }}{% if record.corresp %}，通讯作者 {% endif %}
        </li>
      {% endfor %}
    </ol>
  </div>
{% endif %}

{% if teacherproject_list %}
  <div class="my-4">
    <h6>承担项目情况</h6>
    <hr class="border border-black opacity-100">

    <ol class="my-2">
      {% for record in teacherproject_list %}
        <li>
          {{ record.project.name }}，{{ record.project.source }}，{{ record.project.get_kind_display }}，{{ record.project.start_year }}-{{ record.project.end_year }}，总经费 {{ record.project.total_fund }}，承担经费 {{ record.fund }}
        </li>
      {% endfor %}
    </ol>
  </div>
{% endif %}

{% endblock content %}